# Generated by Django 5.1 on 2024-12-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], default='customer', max_length=10),
        ),
    ]
